### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by NateWr** [ewhanson/authorRequirements#1]
Hi @ewhanson! I did a quick code review of what's here. It looks really good! I don't see any areas where we can limit the code customization here. It looks about as discrete as we can get it. 

Unfortunately, overriding those user form templates are probably going ito require a bit of maintenance over time. But hopefully before too long we'll get them converted to the new forms system and that will be easier.

Some small things I noticed. In the template, instead of:

```
{if !$emailNotRequired}
	{assign var="emailRequired" value=true}
{else}
	{assign var="emailRequired" value=false}
{/if}
```

You can do this to save a few lines:

```
{fbvElement required=!$emailNotRequired ...}
```

As a general rule, with the form classes you should always call the parent methods to ensure that hooks get fired. This ensures someone else could modify your form from a plugin. Noticed at https://github.com/ewhanson/authorRequirements/blob/master/AuthorRequirementsSettingsForm.inc.php#L48 and https://github.com/ewhanson/authorRequirements/blob/master/AuthorRequirementsSettingsForm.inc.php#L56 and https://github.com/ewhanson/authorRequirements/blob/master/AuthorRequirementsSettingsForm.inc.php#L78.

There's a typo in `authorRequrementsSettingsFormSubmit` at https://github.com/ewhanson/authorRequirements/blob/master/templates/settingsForm.tpl#L31.

And there were some places where white-space and indentation are not quite right. You may want to pass it through a formatter. Here are some of the places I noticed:

- [x] https://github.com/ewhanson/authorRequirements/blob/master/AuthorRequirementsPlugin.inc.php#L103-L122
- [x] https://github.com/ewhanson/authorRequirements/blob/master/AuthorRequirementsSettingsForm.inc.php#L20-L38
- [x] https://github.com/ewhanson/authorRequirements/blob/master/AuthorRequirementsSettingsForm.inc.php#L65
- [x] https://github.com/ewhanson/authorRequirements/blob/master/templates/controllers/grid/users/author/form/authorForm.tpl#L39

Great work! Solid, clean code. :+1:

**Comment by NateWr** [comment]
It looks like you've addressed these comments. Can this be closed?

**Comment by ewhanson** [comment]
Yes, all these comments have been addressed.
