### ISSUE TITLE
PHP fatal error

### ISSUE THREAD

**Issue by marlara** [ewhanson/authorRequirements#10]
Hi,

I get this error when trying to configure the plugin: 

`PHP Fatal error:  Declaration of AuthorRequirementsSettingsForm::fetch($request) must be compatible with Form::fetch($request, $template = null, $display = false) in /var/www/ojs/plugins/generic/authorRequirements/AuthorRequirementsSettingsForm.inc.php on line 63`

I have 
OJS versione: 3.3.0.11
PHP version: 8.0.21

**Comment by ewhanson** [comment]
Hi @marlara, I haven't added PHP 8 support for the plugin yet, so thanks for flagging this!

I'll get it updated and a new release made, and I'll post on this issue once that's available.

**Comment by marlara** [comment]
Hi @ewhanson! Any news on this?

Thanks!

**Comment by ewhanson** [comment]
Included in [v1.0.2-1](https://github.com/ewhanson/authorRequirements/releases/tag/v1.0.2-1) release. Closing as complete. Thanks @marlara!
