### ISSUE TITLE
Plugin prevents display of volume editors

### ISSUE THREAD

**Issue by ohilbig01** [ewhanson/authorRequirements#7]
Hi ewhansen,

thank you for your plugin, I would like to use it. I found one bug:
When I activate it, I can't see the volume editors on the landing page.
I think it's because you have to consider templates/controllers/grid/users/author/form/authorForm.tpl, which adds the checkbox
"Identify this contributor as the editor of this volume." to the contributor form. This checkbox is missing if the plugin is enabled.
I inserted the few lines in your authorForm.tpl, maybe this is already the solution.

Regards,
ohilbig01

**Comment by ewhanson** [comment]
Thanks, @ohilbig01. Could you include a screenshot of the page you're referring to with and without the plugin enabled so I can see the change you're talking about?

**Comment by ohilbig01** [comment]
Plugin not enabled:
![pluginNotEnabled](https://user-images.githubusercontent.com/25659317/125928599-c1ff06ec-a0e7-41fb-af0c-40049ec8ffcb.png)

Plugin enabled:
![pluginEnabled](https://user-images.githubusercontent.com/25659317/125928673-92a4ec95-0f14-42fd-b1f9-c39271d83540.png)

As you can see, the last checkbox is gone.

As an easy solution I inserted this lines in your authorForm.tpl:

```
<script>
    $(function() {ldelim}
        $('#editAuthor').pkpHandler(
            '$.pkp.controllers.form.AjaxFormHandler'
        );
    {rdelim});
</script>

+   {if $submission->getData('workType') === $smarty.const.WORK_TYPE_EDITED_VOLUME}
+      {capture assign="additionalCheckboxes"}
+      {fbvElement type="checkbox" label="author.isVolumeEditor" id="isVolumeEditor" checked=$isVolumeEditor}
+    {/capture}
+   {/if}

<form class="pkp_form" id="editAuthor" method="post" action="{url op="updateAuthor" authorId=$authorId}">
```

Works so far for me, but I don't know if this is safe.

**Comment by ewhanson** [comment]
Thanks @ohilbig01, and thanks for flagging the fix as well. I need to double check to make sure that won't affect anything else in either OJS or OPS first, but I'll have an updated release for it soon.

**Comment by ewhanson** [comment]
Thanks @ohilbig01, I've updated the main branch with the fix and will have a release ready and added to the plugin gallery shortly.
